Repository OpenMined/PyDP, pull requests merged in 2020-08, with the labels that each got.

#217 Added setting of l0 and linf sensitivity
  src/bindings/PyDP/algorithms/bounded_functions.cpp
  src/bindings/PyDP/algorithms/distributions.cpp
  src/bindings/PyDP/algorithms/order_statistics.cpp
  src/bindings/PyDP/pydp_lib/helper_class.hpp
  src/bindings/c/c_api.cc
  src/bindings/c/c_api.h
  tests/algorithms/test_distributions.py
Labels: Type: New Feature :heavy_plus_sign:

#272 Improve makefile actions
  Makefile
Labels: Type: Improvement :chart_with_upwards_trend:

#273 Fixed runtime crash due to result()
  pydp/algorithms/_algorithm.py
  tests/algorithms/test_bounded_mean.py
Labels: Status: Review Needed :raising_hand:, Type: Bug :bug:

#264 Allow int64 as dtype
  pydp/algorithms/_algorithm.py
  src/bindings/PyDP/algorithms/bounded_functions.cpp
  src/bindings/PyDP/algorithms/count.cpp
  src/bindings/PyDP/algorithms/order_statistics.cpp
  src/bindings/PyDP/pydp_lib/algorithm_builder.hpp
  tests/algorithms/test_bounded_mean.py
  tests/algorithms/test_count.py
Labels: Status: In Progress :star2:

#271 Fix core crashes due to bound params
  pydp/algorithms/_algorithm.py
  tests/algorithms/test_algorithm.py
Labels: Status: Review Needed :raising_hand:, Type: Bug :bug:

#274 added introduction blog documentation
  docs/introduction.rst
Labels: Status: Review Needed :raising_hand:
